<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyTitle>BackupPower</AssemblyTitle>
        <Product>BackupPower</Product>
        <Copyright>Copyright © 2020-2021</Copyright>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <OutputPath>..\Assemblies\</OutputPath>
        <LangVersion>8</LangVersion>
<!--        <PostBuildEvent>mod update</PostBuildEvent>-->
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="Assembly-CSharp">
        <HintPath>..\..\..\RimWorldWin64_Data\Managed\Assembly-CSharp.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.IMGUIModule">
        <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>..\..\..\RimWorldWin64_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>
</Project>